#集群服务2配置项开始
server:
  port: 10021 #集群服务2端口
eureka:
  server:
    enable-self-preservation: false # 测试时关闭自我保护机制，保证不可用服务及时踢出
  instance:
    hostname: eureka02 #集群服务2主机名称，在hosts中配置了
    instance-id: A01EurekaServerPJPlus-eureka02
  client:
    #    fetch-registry: false
    #    register-with-eureka: false
    service-url:
      defaultZone: http://eureka01:10011/eureka,http://eureka03:10031/eureka #集群服务2需要注册进入集群服务1和集群服务3中
#集群服务2配置项完毕
#集群的spring.application.name需要一致
spring:
  application:
    name: a01eurekaserverpjplus